name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: ikhsan3adi/markdown-translator@v2
        with:
          LANG: zh-CN
      - name: Adding README - Chinese Traditional
        uses: ikhsan3adi/markdown-translator@v2
        with:
          LANG: zh-TW
      - name: Adding README - Hindi"
        uses: ikhsan3adi/markdown-translator@v2
        with:
          LANG: HI
      - name: Adding README - Arabic
        uses: ikhsan3adi/markdown-translator@v2
        with:
          LANG: AR
      - name: Adding README - French
        uses: ikhsan3adi/markdown-translator@v2
        with:
          LANG: FR
      - name: Adding README - Turkish
        uses: ikhsan3adi/markdown-translator@v2
        with:
          LANG: TR
      - name: Adding README - Deutsch
        uses: ikhsan3adi/markdown-translator@v2
        with:
          LANG: DE